[bar/main]
width = 100%
height = 26
background = #33312c
foreground = #ffffff
font-0 = JetBrains Mono:size=10;2

modules-left = i3 xwindow
modules-center = date

padding-left = 0
padding-right = 1
module-margin = 0
separator = " | "

modules-right =  github temperature tray ; Add "battery" in this list to show battery status, you also need to config it in the battery section
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; MODULES
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[module/i3]
type = internal/i3
format = <label-state> <label-mode>
label-focused = %name%
label-focused-background = #e3d10c
label-focused-foreground = #000000
label-focused-padding = 2
label-unfocused = %name%
label-unfocused-padding = 2

[module/date]
type = internal/date
interval = 0.5
date = %m/%d%
time = %I:%M %p
format =  <label>
label = %date%  %time%

[module/xwindow]
type = internal/xwindow
label = %instance%

[module/tray]
type = internal/tray
format-margin = 2px
tray-spacing = 5px

[module/temperature] 
type = internal/temperature

; Seconds to sleep between updates
; Default: 1
interval = 0.01

; Thermal zone to use
; To list all the zone types, run
; $ for i in /sys/class/thermal/thermal_zone*; do echo "$i: $(<$i/type)"; done
; Default: 0
thermal-zone = 2

; Base temperature for where to start the ramp (in degrees celsius)
; Default: 0
base-temperature = 20

; Threshold temperature to display warning label (in degrees celsius)
; Default: 80
warn-temperature = 50

label = CPU TEMP %temperature-c%

label-warn = CPU HOT %temperature-c%

label-warn-foreground = #ff0000

[module/github]
type = internal/github

; Accessing an access token stored in file
token = ${file:/home/user/.ghtoken}

; The github user for the token
; Effectively required; otherwise the module uses a deprecated method of fetching
; notifications, which has stopped working
user = cylin577

; Whether empty notifications should be displayed or not
empty-notifications = false

; Number of seconds in between requests
interval = 15

label = GH: %notifications% Notifs

[module/battery]
type = internal/battery

; This is useful in case the battery never reports 100% charge
; Default: 100
full-at = 95

; format-low once this charge percentage is reached
; Default: 10
; New in version 3.6.0
low-at = 20

; Use the following command to list batteries and adapters:
; $ ls -1 /sys/class/power_supply/
battery = 2400000mWh-battery ; Replace with your own battery name
adapter = 480W-charger ; Replace this too

; If an inotify event haven't been reported in this many
; seconds, manually poll for new values.
;
; Needed as a fallback for systems that don't report events
; on sysfs/procfs.
;
; Disable polling by setting the interval to 0.
;
; Default: 5
poll-interval = 1

label-charging = CHRG %percentage%%

label-discharging = DISCHRG %percentage%%

label-full = FULL

label-low = BATTLOW

format-low = <label-low>
